/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface NFTMarketplaceInterface extends ethers.utils.Interface {
  functions: {
    "ERC721Composable_ValidateFingerprint()": FunctionFragment;
    "ERC721_Interface()": FunctionFragment;
    "ERC721_Received()": FunctionFragment;
    "MAX_BID_DURATION()": FunctionFragment;
    "MIN_BID_DURATION()": FunctionFragment;
    "ONE_MILLION()": FunctionFragment;
    "bidCounterByToken(address,uint256)": FunctionFragment;
    "bidIdByTokenAndBidder(address,uint256,address)": FunctionFragment;
    "bidIndexByBidId(bytes32)": FunctionFragment;
    "cancelBid(address,uint256)": FunctionFragment;
    "getBidByBidder(address,uint256,address)": FunctionFragment;
    "getBidByToken(address,uint256,uint256)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "paymentToken()": FunctionFragment;
    "placeBid(address,uint256,uint256,uint256)": FunctionFragment;
    "removeExpiredBids(address[],uint256[],address[])": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ERC721Composable_ValidateFingerprint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC721_Interface",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC721_Received",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BID_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BID_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONE_MILLION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bidCounterByToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bidIdByTokenAndBidder",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "bidIndexByBidId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidByBidder",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidByToken",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "placeBid",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeExpiredBids",
    values: [string[], BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "ERC721Composable_ValidateFingerprint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC721_Interface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC721_Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BID_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BID_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONE_MILLION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidCounterByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidIdByTokenAndBidder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidIndexByBidId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBidByBidder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeExpiredBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "BidAccepted(bytes32,address,uint256,address,address,uint256)": EventFragment;
    "BidCancelled(bytes32,address,uint256,address)": EventFragment;
    "BidCreated(bytes32,address,uint256,address,uint256,uint256,bytes)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BidAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BidCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BidCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class NFTMarketplace extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: NFTMarketplaceInterface;

  functions: {
    ERC721Composable_ValidateFingerprint(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "ERC721Composable_ValidateFingerprint()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    ERC721_Interface(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "ERC721_Interface()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    ERC721_Received(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "ERC721_Received()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    MAX_BID_DURATION(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "MAX_BID_DURATION()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    MIN_BID_DURATION(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "MIN_BID_DURATION()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    ONE_MILLION(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "ONE_MILLION()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    bidCounterByToken(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "bidCounterByToken(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    bidIdByTokenAndBidder(
      arg0: string,
      arg1: BigNumberish,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "bidIdByTokenAndBidder(address,uint256,address)"(
      arg0: string,
      arg1: BigNumberish,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    bidIndexByBidId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "bidIndexByBidId(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    cancelBid(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelBid(address,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getBidByBidder(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _bidder: string,
      overrides?: CallOverrides
    ): Promise<{
      bidIndex: BigNumber;
      bidId: string;
      bidder: string;
      price: BigNumber;
      expiresAt: BigNumber;
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: BigNumber;
    }>;

    "getBidByBidder(address,uint256,address)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _bidder: string,
      overrides?: CallOverrides
    ): Promise<{
      bidIndex: BigNumber;
      bidId: string;
      bidder: string;
      price: BigNumber;
      expiresAt: BigNumber;
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: BigNumber;
    }>;

    getBidByToken(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
      2: BigNumber;
      3: BigNumber;
    }>;

    "getBidByToken(address,uint256,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
      2: BigNumber;
      3: BigNumber;
    }>;

    onERC721Received(
      _from: string,
      arg1: string,
      _tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      _from: string,
      arg1: string,
      _tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    paymentToken(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "paymentToken()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "placeBid(address,uint256,uint256,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _price: BigNumberish,
      _duration: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "placeBid(address,uint256,uint256,uint256,bytes)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _price: BigNumberish,
      _duration: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    removeExpiredBids(
      _tokenAddresses: string[],
      _tokenIds: BigNumberish[],
      _bidders: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeExpiredBids(address[],uint256[],address[])"(
      _tokenAddresses: string[],
      _tokenIds: BigNumberish[],
      _bidders: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  ERC721Composable_ValidateFingerprint(
    overrides?: CallOverrides
  ): Promise<string>;

  "ERC721Composable_ValidateFingerprint()"(
    overrides?: CallOverrides
  ): Promise<string>;

  ERC721_Interface(overrides?: CallOverrides): Promise<string>;

  "ERC721_Interface()"(overrides?: CallOverrides): Promise<string>;

  ERC721_Received(overrides?: CallOverrides): Promise<string>;

  "ERC721_Received()"(overrides?: CallOverrides): Promise<string>;

  MAX_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

  "MAX_BID_DURATION()"(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

  "MIN_BID_DURATION()"(overrides?: CallOverrides): Promise<BigNumber>;

  ONE_MILLION(overrides?: CallOverrides): Promise<BigNumber>;

  "ONE_MILLION()"(overrides?: CallOverrides): Promise<BigNumber>;

  bidCounterByToken(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "bidCounterByToken(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  bidIdByTokenAndBidder(
    arg0: string,
    arg1: BigNumberish,
    arg2: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "bidIdByTokenAndBidder(address,uint256,address)"(
    arg0: string,
    arg1: BigNumberish,
    arg2: string,
    overrides?: CallOverrides
  ): Promise<string>;

  bidIndexByBidId(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "bidIndexByBidId(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cancelBid(
    _tokenAddress: string,
    _tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelBid(address,uint256)"(
    _tokenAddress: string,
    _tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getBidByBidder(
    _tokenAddress: string,
    _tokenId: BigNumberish,
    _bidder: string,
    overrides?: CallOverrides
  ): Promise<{
    bidIndex: BigNumber;
    bidId: string;
    bidder: string;
    price: BigNumber;
    expiresAt: BigNumber;
    0: BigNumber;
    1: string;
    2: string;
    3: BigNumber;
    4: BigNumber;
  }>;

  "getBidByBidder(address,uint256,address)"(
    _tokenAddress: string,
    _tokenId: BigNumberish,
    _bidder: string,
    overrides?: CallOverrides
  ): Promise<{
    bidIndex: BigNumber;
    bidId: string;
    bidder: string;
    price: BigNumber;
    expiresAt: BigNumber;
    0: BigNumber;
    1: string;
    2: string;
    3: BigNumber;
    4: BigNumber;
  }>;

  getBidByToken(
    _tokenAddress: string,
    _tokenId: BigNumberish,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: string;
    2: BigNumber;
    3: BigNumber;
  }>;

  "getBidByToken(address,uint256,uint256)"(
    _tokenAddress: string,
    _tokenId: BigNumberish,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: string;
    2: BigNumber;
    3: BigNumber;
  }>;

  onERC721Received(
    _from: string,
    arg1: string,
    _tokenId: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "onERC721Received(address,address,uint256,bytes)"(
    _from: string,
    arg1: string,
    _tokenId: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  paymentToken(overrides?: CallOverrides): Promise<string>;

  "paymentToken()"(overrides?: CallOverrides): Promise<string>;

  "placeBid(address,uint256,uint256,uint256)"(
    _tokenAddress: string,
    _tokenId: BigNumberish,
    _price: BigNumberish,
    _duration: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "placeBid(address,uint256,uint256,uint256,bytes)"(
    _tokenAddress: string,
    _tokenId: BigNumberish,
    _price: BigNumberish,
    _duration: BigNumberish,
    _fingerprint: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  removeExpiredBids(
    _tokenAddresses: string[],
    _tokenIds: BigNumberish[],
    _bidders: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeExpiredBids(address[],uint256[],address[])"(
    _tokenAddresses: string[],
    _tokenIds: BigNumberish[],
    _bidders: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    ERC721Composable_ValidateFingerprint(
      overrides?: CallOverrides
    ): Promise<string>;

    "ERC721Composable_ValidateFingerprint()"(
      overrides?: CallOverrides
    ): Promise<string>;

    ERC721_Interface(overrides?: CallOverrides): Promise<string>;

    "ERC721_Interface()"(overrides?: CallOverrides): Promise<string>;

    ERC721_Received(overrides?: CallOverrides): Promise<string>;

    "ERC721_Received()"(overrides?: CallOverrides): Promise<string>;

    MAX_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_BID_DURATION()"(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_BID_DURATION()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_MILLION(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_MILLION()"(overrides?: CallOverrides): Promise<BigNumber>;

    bidCounterByToken(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bidCounterByToken(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bidIdByTokenAndBidder(
      arg0: string,
      arg1: BigNumberish,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "bidIdByTokenAndBidder(address,uint256,address)"(
      arg0: string,
      arg1: BigNumberish,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<string>;

    bidIndexByBidId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bidIndexByBidId(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelBid(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelBid(address,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getBidByBidder(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _bidder: string,
      overrides?: CallOverrides
    ): Promise<{
      bidIndex: BigNumber;
      bidId: string;
      bidder: string;
      price: BigNumber;
      expiresAt: BigNumber;
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: BigNumber;
    }>;

    "getBidByBidder(address,uint256,address)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _bidder: string,
      overrides?: CallOverrides
    ): Promise<{
      bidIndex: BigNumber;
      bidId: string;
      bidder: string;
      price: BigNumber;
      expiresAt: BigNumber;
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: BigNumber;
    }>;

    getBidByToken(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
      2: BigNumber;
      3: BigNumber;
    }>;

    "getBidByToken(address,uint256,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
      2: BigNumber;
      3: BigNumber;
    }>;

    onERC721Received(
      _from: string,
      arg1: string,
      _tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,address,uint256,bytes)"(
      _from: string,
      arg1: string,
      _tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    paymentToken(overrides?: CallOverrides): Promise<string>;

    "paymentToken()"(overrides?: CallOverrides): Promise<string>;

    "placeBid(address,uint256,uint256,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _price: BigNumberish,
      _duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "placeBid(address,uint256,uint256,uint256,bytes)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _price: BigNumberish,
      _duration: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    removeExpiredBids(
      _tokenAddresses: string[],
      _tokenIds: BigNumberish[],
      _bidders: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "removeExpiredBids(address[],uint256[],address[])"(
      _tokenAddresses: string[],
      _tokenIds: BigNumberish[],
      _bidders: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    BidAccepted(
      _id: null,
      _tokenAddress: string | null,
      _tokenId: BigNumberish | null,
      _bidder: null,
      _seller: string | null,
      _price: null
    ): EventFilter;

    BidCancelled(
      _id: null,
      _tokenAddress: string | null,
      _tokenId: BigNumberish | null,
      _bidder: string | null
    ): EventFilter;

    BidCreated(
      _id: null,
      _tokenAddress: string | null,
      _tokenId: BigNumberish | null,
      _bidder: string | null,
      _price: null,
      _expiresAt: null,
      _fingerprint: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    ERC721Composable_ValidateFingerprint(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ERC721Composable_ValidateFingerprint()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ERC721_Interface(overrides?: CallOverrides): Promise<BigNumber>;

    "ERC721_Interface()"(overrides?: CallOverrides): Promise<BigNumber>;

    ERC721_Received(overrides?: CallOverrides): Promise<BigNumber>;

    "ERC721_Received()"(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_BID_DURATION()"(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_BID_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_BID_DURATION()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_MILLION(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_MILLION()"(overrides?: CallOverrides): Promise<BigNumber>;

    bidCounterByToken(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bidCounterByToken(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bidIdByTokenAndBidder(
      arg0: string,
      arg1: BigNumberish,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bidIdByTokenAndBidder(address,uint256,address)"(
      arg0: string,
      arg1: BigNumberish,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bidIndexByBidId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bidIndexByBidId(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelBid(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelBid(address,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getBidByBidder(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _bidder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBidByBidder(address,uint256,address)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _bidder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBidByToken(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBidByToken(address,uint256,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC721Received(
      _from: string,
      arg1: string,
      _tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      _from: string,
      arg1: string,
      _tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    paymentToken(overrides?: CallOverrides): Promise<BigNumber>;

    "paymentToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    "placeBid(address,uint256,uint256,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _price: BigNumberish,
      _duration: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "placeBid(address,uint256,uint256,uint256,bytes)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _price: BigNumberish,
      _duration: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    removeExpiredBids(
      _tokenAddresses: string[],
      _tokenIds: BigNumberish[],
      _bidders: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeExpiredBids(address[],uint256[],address[])"(
      _tokenAddresses: string[],
      _tokenIds: BigNumberish[],
      _bidders: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ERC721Composable_ValidateFingerprint(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ERC721Composable_ValidateFingerprint()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC721_Interface(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ERC721_Interface()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC721_Received(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ERC721_Received()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_BID_DURATION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MAX_BID_DURATION()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MIN_BID_DURATION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MIN_BID_DURATION()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ONE_MILLION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ONE_MILLION()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bidCounterByToken(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bidCounterByToken(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bidIdByTokenAndBidder(
      arg0: string,
      arg1: BigNumberish,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bidIdByTokenAndBidder(address,uint256,address)"(
      arg0: string,
      arg1: BigNumberish,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bidIndexByBidId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bidIndexByBidId(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelBid(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelBid(address,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getBidByBidder(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _bidder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBidByBidder(address,uint256,address)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _bidder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBidByToken(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBidByToken(address,uint256,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      _from: string,
      arg1: string,
      _tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      _from: string,
      arg1: string,
      _tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paymentToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paymentToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "placeBid(address,uint256,uint256,uint256)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _price: BigNumberish,
      _duration: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "placeBid(address,uint256,uint256,uint256,bytes)"(
      _tokenAddress: string,
      _tokenId: BigNumberish,
      _price: BigNumberish,
      _duration: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    removeExpiredBids(
      _tokenAddresses: string[],
      _tokenIds: BigNumberish[],
      _bidders: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeExpiredBids(address[],uint256[],address[])"(
      _tokenAddresses: string[],
      _tokenIds: BigNumberish[],
      _bidders: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
